name: fcis_guide
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  fluttertoast: ^8.2.4
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  flutter_expandable_text: ^1.0.0
  custom_refresh_indicator: ^3.1.0
  flutter_easyloading: any


  flutter_bloc: ^8.1.4
  multiple_result: ^5.1.0

  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1

  firebase_core: ^2.16.0
  firebase_auth: ^4.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.5.3
  firebase_crashlytics: ^3.4.18

  connectivity_plus: ^5.0.2

  url_launcher: ^6.2.6
  share_plus: ^7.2.2

flutter_native_splash:
  color: "#ffffff"
  image: images/app_logo.png
  background_image: images/app_logo.png
  android_12:
    image: images/app_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - images/
